#Sources 
:sources: 
  AccountAdapter: 
    :poll_interval: 300
 
:development: 
  :licensefile: settings/license.key
  :syncserver: http://localhost:9292/api/application/
  :redis: localhost:6379
:production: 
  :licensefile: settings/license.key
  :syncserver: http://localhost:9292/api/application/
  :redis: localhost:6379
:test: 
  :licensefile: settings/license.key
  :syncserver: http://localhost:9292/api/application/
  :redis: localhost:6379
